apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-backend-api
description: demo backend api pipeline
serialPipeline:
  stages:
  - targetId: demo-backend-api
    profiles: [dev]
  - targetId: demo-backend-api-prod
    profiles: [prod]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25, 50]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-backend-api
description: Cloud Run development service
run:
  location: projects/event-encraft-202310/locations/asia-northeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-backend-api-prod
description: Cloud Run production service
run:
  location: projects/event-encraft-202310/locations/asia-northeast1
