apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-backend-api
description: demo backend api pipeline
serialPipeline:
  stages:
  - targetId: demo-backend-api-dev
    profiles: [dev]
  - targetId: demo-backend-api-prod
    profiles: [prod]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25, 50, 75]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-backend-api-dev
description: Cloud Run development service
run:
  location: projects/cloud-run-deploy-demo/locations/asia-northeast1  # Change project-id
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: demo-backend-api-prod
description: Cloud Run production service
run:
  location: projects/cloud-run-deploy-demo/locations/asia-northeast1  # Change project-id
