apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-backend-api-prod
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"   # 最小スケール数
        autoscaling.knative.dev/target: "100"   # 同時に処理できるリクエストの最大数
    spec:
      containers:
      - image: demo-backend-api
        ports:
        - containerPort: 8080 # コンテナのポート
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
      serviceAccountName: demo-backend-api-prod # from-param: ${service_account}
      timeoutSeconds: 300 # リクエストのタイムアウト時間（秒）