name: Trigger Cloud Build on branch deletion

on:
  delete:
    branches:
      - '**'

permissions:
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SA_ID }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds triggers run ${{ vars.CLOUD_BUILD_TRIGGER_NAME }} --region=${{ vars.CLOUD_BUILD_REGION }} --substitutions=_BRANCH_NAME="${{ github.event.ref }}"